#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>

static int current_seed_id = 1;

static void die_perror(const char *msg) {
    perror(msg);
    exit(EXIT_FAILURE);
}

static void ensure_corpus_environment(void) {
    if (mkdir("zend_corpus", 0777) != 0 && errno != EEXIST) {
        die_perror("mkdir");
    }
}

static void emit_seed(const char *payload) {
    char filepath[256];
    FILE *f = NULL;

    if (snprintf(filepath, sizeof(filepath), "zend_corpus/seed_%05d.php", current_seed_id++) >= (int)sizeof(filepath)) {
        fprintf(stderr, "path too long\n");
        exit(EXIT_FAILURE);
    }

    f = fopen(filepath, "wb");
    if (!f) {
        die_perror("fopen");
    }

    if (fputs("<?php\nerror_reporting(0);\n", f) == EOF) {
        die_perror("fputs");
    }

    if (fputs(payload, f) == EOF) {
        die_perror("fputs");
    }

    if (fputs("\n?>\n", f) == EOF) {
        die_perror("fputs");
    }

    if (fclose(f) != 0) {
        die_perror("fclose");
    }
}

static void build_zend_hash_payloads(void) {
    emit_seed("$h=[]; for($i=0;$i<1024;$i++){$h[$i]=1;}");
    emit_seed("$h=[]; for($i=0;$i<1024;$i++){$h[(string)$i]=1;}");
    emit_seed("$h=[]; for($i=0;$i<1024;$i++){$h[$i<<2]=1;}");
    emit_seed("$h=[]; for($i=0;$i<2048;$i++){$h[str_repeat('A',$i%256)]=$i;}");
    emit_seed("$h=array_fill(0,1024,'B'); $h=array_flip($h);");
    emit_seed("$h=[]; for($i=0;$i<1024;$i++){$h[$i]=&$h;}");
    emit_seed("$a=[1,2,3]; $b=[4,5,6]; $c=array_merge($a,$b); $c[]=$c;");
    emit_seed("$h=[]; for($i=0;$i<512;$i++){$h[str_pad((string)$i,1024,'X')]=1;}");
    emit_seed("$h=[1=>'a', '1'=>'b', 1.0=>'c', true=>'d'];");
    emit_seed("$a=range(1,1024); unset($a[512]); $a=array_values($a);");
    emit_seed("$a=range(1,1024); array_splice($a, 512, 10, [1,2,3]);");
    emit_seed("$a=array_fill_keys(range(1,512), 'A');");
    emit_seed("$a=['x'=>1]; $b=&$a['x']; unset($a['x']); $b=2;");
    emit_seed("$a=['y'=>['z'=>1]]; $b=&$a['y']['z']; unset($a['y']); $b=2;");
    emit_seed("$k='k'; $h=[$k=>1]; $k='l'; $h[$k]=2;");
    emit_seed("$h=[]; foreach(range(1,256) as $v){$h[$v]=function()use(&$h){return $h;};}");
    emit_seed("$h=array_fill(0,128,array_fill(0,128,'C'));");
    emit_seed("$vars=['a'=>1,'b'=>2,'c'=>3]; extract($vars, EXTR_REFS);");
    emit_seed("$a=1; $b=2; $c=3; compact('a','b','c');");
    emit_seed("$a=['x'=>1]; array_walk_recursive($a, function(&$v){$v=2;});");
    emit_seed("$a=[1,2]; $b=[3,4]; array_multisort($a, SORT_DESC, $b, SORT_ASC);");
    emit_seed("$a=range(1,256); $b=array_chunk($a, 3);");
    emit_seed("$a=array_combine(range(1,128), range(128,255));");
    emit_seed("$a=array_pad([], 1024, 'X');");
    emit_seed("$a=[1,2]; $a=array_replace_recursive($a, [$a]);");
    emit_seed("$a=range(1,10); $b=array_reduce($a, function($c,$i){return $c+$i;}, 0);");
    emit_seed("$a=[1,2,3]; array_shift($a); array_unshift($a, 4);");
    emit_seed("$a=[1,2,3]; array_pop($a); array_push($a, 4);");
    emit_seed("$a=[1,2]; extract($a, EXTR_SKIP);");
    emit_seed("$a=array_intersect_key(['a'=>1], ['a'=>2]);");
    emit_seed("$a=array_diff_assoc(['a'=>1], ['a'=>2]);");
    emit_seed("$a=array_udiff([1], [2], function($x,$y){return $x<=>$y;});");
    emit_seed("$a=array_uintersect([1], [2], function($x,$y){return $x<=>$y;});");
    emit_seed("$a=[1,2]; $b=&$a[0]; array_splice($a, 0, 1);");
    emit_seed("$a=range(1,100); array_walk($a, function(&$v, $k) use (&$a){ unset($a[$k+1]); });");
    emit_seed("$a=range(1,10); array_filter($a, function($v) use (&$a){ $a[]=$v; return true; });");
    emit_seed("$h=[]; for($i=0;$i<100;$i++){ $h[$i]=str_repeat('A', 1000); } array_rand($h, 50);");
    emit_seed("$h=['a'=>1, 'b'=>2]; $r=&$h['a']; unset($h['a']); $h['c']=3;");
    emit_seed("$a=[1]; $a[1]=&$a[0]; $a[0]=2;");
    emit_seed("$h=[]; for($i=0;$i<100;$i++){ $k=random_bytes(10); $h[$k]=$i; }");
}

static void build_zend_alloc_payloads(void) {
    emit_seed("$s=str_repeat('A', 1048576);");
    emit_seed("$s=str_pad('A', 1048576, 'B', STR_PAD_BOTH);");
    emit_seed("$s=implode('', array_fill(0, 1024, 'C'));");
    emit_seed("$s=join('X', range(1, 1024));");
    emit_seed("$a=str_split(str_repeat('D', 1024), 2);");
    emit_seed("$s=wordwrap(str_repeat('E', 1024), 10, '\\n', true);");
    emit_seed("$s=str_shuffle(str_repeat('F', 512));");
    emit_seed("$s=strrev(str_repeat('G', 1024));");
    emit_seed("$s=strtolower(str_repeat('H', 1024));");
    emit_seed("$s=strtoupper(str_repeat('i', 1024));");
    emit_seed("$s=ucwords(str_repeat('j ', 512));");
    emit_seed("$s=str_replace('A', 'BB', str_repeat('A', 512));");
    emit_seed("$s=str_ireplace('a', 'BB', str_repeat('A', 512));");
    emit_seed("$s=substr_replace(str_repeat('K', 512), 'L', 100, 200);");
    emit_seed("$s=substr(str_repeat('M', 1024), 512, 128);");
    emit_seed("$s=function_exists('iconv') ? iconv('UTF-8', 'UTF-16LE', str_repeat('N', 1024)) : '';");
    emit_seed("$s=function_exists('mb_convert_encoding') ? mb_convert_encoding(str_repeat('O', 1024), 'UTF-16', 'UTF-8') : '';");
    emit_seed("$s=base64_encode(random_bytes(1024));");
    emit_seed("$s=base64_decode(base64_encode(random_bytes(1024)));");
    emit_seed("$s=bin2hex(random_bytes(512));");
    emit_seed("$s=hex2bin(bin2hex(random_bytes(512)));");
    emit_seed("$s=pack('N*', 1, 2, 3, 4, 5);");
    emit_seed("$a=unpack('N*', pack('N*', 1, 2, 3));");
    emit_seed("$s=gzcompress(str_repeat('P', 1024), 9);");
    emit_seed("$s=gzuncompress(gzcompress(str_repeat('Q', 1024), 9));");
    emit_seed("$s=gzdeflate(str_repeat('R', 1024), 9);");
    emit_seed("$s=gzinflate(gzdeflate(str_repeat('S', 1024), 9));");
    emit_seed("$s=gzencode(str_repeat('T', 1024), 9);");
    emit_seed("$s=gzdecode(gzencode(str_repeat('U', 1024), 9));");
    emit_seed("$s=serialize(array_fill(0, 128, 'V'));");
    emit_seed("$a=unserialize(serialize(array_fill(0, 128, 'W')));");
    emit_seed("$s=json_encode(array_fill(0, 128, 'X'));");
    emit_seed("$a=json_decode(json_encode(array_fill(0, 128, 'Y')), true);");
}

static void build_generator_and_fiber_payloads(void) {
    emit_seed("function g(){yield 1; yield 2; yield 3;} $g=g(); foreach($g as $v){}");
    emit_seed("function g(){yield from [1,2,3,4,5];} foreach(g() as $v){}");
    emit_seed("function g(){for($i=0;$i<32;$i++){yield $i;}} $g=g(); iterator_to_array($g);");
    emit_seed("function g(){yield 'a'=>1; yield 'b'=>2;} $g=g(); foreach($g as $k=>$v){}");
    emit_seed("function g(){try{yield 1;}finally{yield 2;}} $g=g(); foreach($g as $v){}");
    emit_seed("function g(){yield 1; throw new Exception('x');} try{$g=g();$g->next();}catch(Throwable $e){}");
    emit_seed("function g(){yield from range(1,128);} foreach(g() as $v){}");
    emit_seed("$f=function($x)use(&$f){return $x?$f($x-1):0;}; $f(16);");
    emit_seed("function g(){yield 1; yield 2;} $g=g(); $g->rewind(); $g->next();");
    emit_seed("function g(){yield 1; yield 2;} $g=g(); $g->valid();");
    emit_seed("function g(){yield 1; yield 2;} $g=g(); $g->current();");
    emit_seed("function g(){yield 1; yield 2;} $g=g(); $g->key();");
    emit_seed("function g(){yield 1; return 2;} $g=g(); foreach($g as $v){} $g->getReturn();");
    emit_seed("function g(){yield from [1,[2,[3]]];} foreach(g() as $v){}");
    emit_seed("function g(){for($i=0;$i<10;$i++){yield str_repeat('A',$i);}} foreach(g() as $v){}");
    emit_seed("function g(){yield 1; yield from [2,3]; yield 4;} foreach(g() as $v){}");
    emit_seed("function g(){if(rand(0,1)){yield 1;}else{yield 2;}} foreach(g() as $v){}");
    emit_seed("function g(){yield fopen('php://memory','r');} foreach(g() as $v){}");
    emit_seed("function g(){yield new stdClass();} foreach(g() as $v){}");
    emit_seed("function g(){yield from array_fill(0,64,'X');} iterator_to_array(g());");
    emit_seed("function g(){yield 1=>2; yield 3=>4;} foreach(g() as $k=>$v){}");
    emit_seed("function g(){yield from new ArrayIterator([1,2,3]);} foreach(g() as $v){}");
    emit_seed("function g(){for($i=0;$i<100;$i++){yield $i=>$i*$i;}} foreach(g() as $k=>$v){}");
    emit_seed("function g(){yield from []; yield 1;} foreach(g() as $v){}");
    emit_seed("function g(){yield null; yield false; yield true;} foreach(g() as $v){}");
    emit_seed("function g(){yield 1.1; yield INF; yield NAN;} foreach(g() as $v){}");
    emit_seed("function g(){yield ['a'=>1]; yield ['b'=>2];} foreach(g() as $v){}");
    emit_seed("function g(){yield from range(-100,100);} foreach(g() as $v){}");
    emit_seed("function g(){yield str_repeat('Z',1024);} foreach(g() as $v){}");
    emit_seed("function g(){yield random_bytes(32);} foreach(g() as $v){}");
    emit_seed("function g(){yield pack('N',1234);} foreach(g() as $v){}");
    emit_seed("function g(){yield json_encode(['x'=>1]);} foreach(g() as $v){}");
    emit_seed("function g(){yield serialize(['x'=>1]);} foreach(g() as $v){}");
    emit_seed("function g(){yield gzcompress(str_repeat('A',128));} foreach(g() as $v){}");
    emit_seed("function g(){yield base64_encode(random_bytes(64));} foreach(g() as $v){}");
    emit_seed("function g(){yield hash('sha256','abc');} foreach(g() as $v){}");
    emit_seed("function g(){yield from [new ArrayObject(),new stdClass()];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [[1,2],[3,4]];} foreach(g() as $v){}");
    emit_seed("function g(){for($i=0;$i<8;$i++){yield function()use($i){return $i;};}} foreach(g() as $v){$v();}");
    emit_seed("function g(){yield from array_chunk(range(1,64),4);} foreach(g() as $v){}");
    emit_seed("function g(){yield from str_split(str_repeat('A',256),8);} foreach(g() as $v){}");
    emit_seed("function g(){yield from preg_split('//','abcdef');} foreach(g() as $v){}");
    emit_seed("function g(){yield from explode(',',str_repeat('a,',64));} foreach(g() as $v){}");
    emit_seed("function g(){yield from array_fill(0,128,random_int(0,1000));} foreach(g() as $v){}");
    emit_seed("function g(){yield fopen('php://temp','r+');} foreach(g() as $v){}");
    emit_seed("function g(){yield from [tmpfile(),tmpfile()];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [STDIN,STDOUT,STDERR];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [new SplFixedArray(4)];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [new SplQueue(),new SplStack()];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [new DateTime(),new DateInterval('P1D')];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [new Exception('x')];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [range(1,8),range(9,16)];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [array_fill(0,32,'A')];} foreach(g() as $v){}");
    emit_seed("function g(){yield from [str_repeat('B',2048)];} foreach(g() as $v){}");
    emit_seed("$fiber=new Fiber(function(){return 1;}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){Fiber::suspend(1);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){Fiber::suspend(1);}); $fiber->start(); $fiber->resume();");
    emit_seed("$fiber=new Fiber(function(){return random_int(1,100);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return str_repeat('A',1024);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return fopen('php://memory','r');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return new stdClass();}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){throw new Exception('fiber');}); try{$fiber->start();}catch(Throwable $e){}");
    emit_seed("$fiber=new Fiber(function(){Fiber::suspend(); return 1;}); $fiber->start(); $fiber->resume();");
    emit_seed("$fiber=new Fiber(function(){for($i=0;$i<10;$i++){Fiber::suspend($i);}}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return gzcompress(str_repeat('A',64));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return base64_encode(random_bytes(32));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return hash('sha1','abc');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return json_encode(range(1,16));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return serialize(['x'=>1]);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return unpack('N',pack('N',123));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return array_fill(0,64,'Z');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return new ArrayObject(range(1,16));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return new SplFixedArray(8);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return tmpfile();}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return fopen('php://temp','r+');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return preg_match('/a+/','aaaa');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return preg_split('/a/','a,a,a');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return explode(',',str_repeat('a,',16));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return implode(',',range(1,16));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return bin2hex(random_bytes(16));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return hex2bin(bin2hex(random_bytes(16)));}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return parse_url('http://example.com/test');}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return http_build_query(['a'=>1]);}); $fiber->start();");
    emit_seed("$fiber=new Fiber(function(){return range(-32,32);}); $fiber->start();");
}
static void build_reflection_and_object_payloads(void) {
    emit_seed("$r=new ReflectionClass('stdClass');");
    emit_seed("$r=new ReflectionObject(new stdClass());");
    emit_seed("$r=new ReflectionFunction('strlen');");
    emit_seed("$r=new ReflectionExtension('Core');");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append');");
    emit_seed("$r=new ReflectionParameter(['ArrayObject','append'],0);");
    emit_seed("$r=new ReflectionClass('Exception'); $r->newInstance('x');");
    emit_seed("$r=new ReflectionClass('stdClass'); $r->newInstanceWithoutConstructor();");
    emit_seed("$r=new ReflectionFunction(function($x){return $x;}); $r->invoke(1);");
    emit_seed("$r=new ReflectionFunction('range'); $r->invoke(1,16);");
    emit_seed("$r=new ReflectionFunction('json_encode'); $r->invoke(['a'=>1]);");
    emit_seed("$r=new ReflectionFunction('serialize'); $r->invoke(['x'=>1]);");
    emit_seed("$r=new ReflectionFunction('hash'); $r->invoke('sha256','abc');");
    emit_seed("$r=new ReflectionClass('ArrayObject'); $o=$r->newInstance([1,2,3]);");
    emit_seed("$r=new ReflectionClass('SplFixedArray'); $o=$r->newInstance(8);");
    emit_seed("$r=new ReflectionClass('DateTime'); $o=$r->newInstance();");
    emit_seed("$r=new ReflectionClass('ArrayIterator'); $o=$r->newInstance([1,2,3]);");
    emit_seed("$r=new ReflectionGenerator((function(){yield 1;})());");
    emit_seed("$r=new ReflectionFiber(new Fiber(function(){}));");
    emit_seed("$r=new ReflectionClass('stdClass'); $r->getMethods();");
    emit_seed("$r=new ReflectionClass('Exception'); $r->getProperties();");
    emit_seed("$r=new ReflectionClass('ArrayObject'); $r->getConstants();");
    emit_seed("$r=new ReflectionClass('DateTime'); $r->getInterfaces();");
    emit_seed("$r=new ReflectionClass('SplQueue'); $r->getTraits();");
    emit_seed("$r=new ReflectionClass('SplStack'); $r->implementsInterface('Iterator');");
    emit_seed("$r=new ReflectionClass('ArrayObject'); $r->isInstantiable();");
    emit_seed("$r=new ReflectionClass('Closure'); $r->isCloneable();");
    emit_seed("$r=new ReflectionClass('Generator'); $r->isInternal();");
    emit_seed("$r=new ReflectionClass('Fiber'); $r->isUserDefined();");
    emit_seed("$r=new ReflectionClass('Exception'); $r->isSubclassOf('Throwable');");
    emit_seed("$r=new ReflectionClass('RuntimeException'); $r->getParentClass();");
    emit_seed("$r=new ReflectionClass('ArrayObject'); $r->getDefaultProperties();");
    emit_seed("$r=new ReflectionClass('DateInterval'); $r->getExtension();");
    emit_seed("$r=new ReflectionClass('SplPriorityQueue'); $r->getExtensionName();");
    emit_seed("$r=new ReflectionClass('stdClass'); $r->getShortName();");
    emit_seed("$r=new ReflectionClass('Exception'); $r->getNamespaceName();");
    emit_seed("$r=new ReflectionClass('ArrayObject'); $r->inNamespace();");
    emit_seed("$r=new ReflectionClass('Closure'); $r->getDocComment();");
    emit_seed("$r=new ReflectionClass('Generator'); $r->getFileName();");
    emit_seed("$r=new ReflectionClass('Fiber'); $r->getStartLine();");
    emit_seed("$r=new ReflectionClass('Fiber'); $r->getEndLine();");
    emit_seed("$r=new ReflectionFunction('strlen'); $r->getNumberOfParameters();");
    emit_seed("$r=new ReflectionFunction('range'); $r->getNumberOfRequiredParameters();");
    emit_seed("$r=new ReflectionFunction('explode'); $r->returnsReference();");
    emit_seed("$r=new ReflectionFunction('implode'); $r->isInternal();");
    emit_seed("$r=new ReflectionFunction('trim'); $r->isClosure();");
    emit_seed("$r=new ReflectionFunction(function(){return 1;}); $r->isUserDefined();");
    emit_seed("$r=new ReflectionFunction(function($x){return $x;}); $r->getStaticVariables();");
    emit_seed("$r=new ReflectionFunction(function()use(&$x){}); $r->getClosureUsedVariables();");
    emit_seed("$r=new ReflectionFunction(function(){yield 1;}); $r->isGenerator();");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append'); $r->isPublic();");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append'); $r->isStatic();");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append'); $r->getParameters();");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append'); $r->getReturnType();");
    emit_seed("$r=new ReflectionMethod('ArrayObject','append'); $r->invoke(new ArrayObject(),1);");
    emit_seed("$r=new ReflectionProperty('Exception','message');");
    emit_seed("$r=new ReflectionClass('Exception'); $o=$r->newInstance('x');");
    emit_seed("$p=new ReflectionProperty('Exception','message'); $p->setAccessible(true);");
    emit_seed("$o=new stdClass(); $o->x=1; $r=new ReflectionObject($o);");
    emit_seed("$o=new ArrayObject([1,2,3]); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplFixedArray(8); $r=new ReflectionObject($o);");
    emit_seed("$o=new DateTime(); $r=new ReflectionObject($o);");
    emit_seed("$o=new Exception('x'); $r=new ReflectionObject($o);");
    emit_seed("$o=new ArrayIterator([1,2,3]); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplQueue(); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplStack(); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplHeap(); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplPriorityQueue(); $r=new ReflectionObject($o);");
    emit_seed("$o=new SplObjectStorage(); $r=new ReflectionObject($o);");
    emit_seed("$o=new WeakMap(); $r=new ReflectionObject($o);");
    emit_seed("$o=WeakReference::create(new stdClass());");
    emit_seed("$o=new ArrayObject(); $o['x']=1;");
    emit_seed("$o=new ArrayIterator(range(1,16)); foreach($o as $v){}");
    emit_seed("$o=new SplQueue(); for($i=0;$i<16;$i++){$o->enqueue($i);} while(!$o->isEmpty()){$o->dequeue();}");
    emit_seed("$o=new SplStack(); for($i=0;$i<16;$i++){$o->push($i);} while(!$o->isEmpty()){$o->pop();}");
    emit_seed("$o=new SplFixedArray(32); for($i=0;$i<32;$i++){$o[$i]=$i;}");
    emit_seed("$o=new SplPriorityQueue(); for($i=0;$i<16;$i++){$o->insert($i,$i);} foreach($o as $v){}");
    emit_seed("$o=new SplObjectStorage(); $x=new stdClass(); $o->attach($x);");
    emit_seed("$o=new ArrayObject(range(1,32)); serialize($o);");
    emit_seed("$o=new SplFixedArray(16); serialize($o);");
    emit_seed("$o=new ArrayIterator(range(1,16)); serialize($o);");
    emit_seed("$o=new stdClass(); $o->x=&$o;");
    emit_seed("$o=new stdClass(); $o->a=new stdClass(); $o->a->b=$o;");
    emit_seed("$o=new ArrayObject(); $o['self']=$o;");
    emit_seed("$o=new SplObjectStorage(); $o->attach($o);");
    emit_seed("$o=new stdClass(); $w=WeakReference::create($o); unset($o);");
    emit_seed("$m=new WeakMap(); $o=new stdClass(); $m[$o]=str_repeat('A',64);");
    emit_seed("class A{public $x=1;} $o=new A(); clone $o;");
    emit_seed("class A{function __toString(){return 'A';}} $o=new A(); (string)$o;");
    emit_seed("class A{function __invoke(){return 1;}} $o=new A(); $o();");
    emit_seed("class A{function __get($n){return 1;}} $o=new A(); $o->x;");
    emit_seed("class A{function __set($n,$v){$this->$n=$v;}} $o=new A(); $o->x=1;");
    emit_seed("class A{function __isset($n){return true;}} $o=new A(); isset($o->x);");
    emit_seed("class A{function __unset($n){}} $o=new A(); unset($o->x);");
    emit_seed("class A{function __sleep(){return [];}} serialize(new A());");
    emit_seed("class A{function __wakeup(){$this->x=1;}} unserialize('O:1:\"A\":0:{}');");
    emit_seed("class A{function __debugInfo(){return ['x'=>1];}} var_dump(new A());");
    emit_seed("class A{public static function __set_state($a){return new A();}} var_export(new A(),true);");
    emit_seed("class A{function __destruct(){$x=1;}} $o=new A(); unset($o);");
    emit_seed("class A{function __clone(){$this->x=1;}} $o=new A(); clone $o;");
    emit_seed("class A{public $x;} $o=new A(); $o->x=$o;");
    emit_seed("class A{public $x;} $a=new A(); $b=new A(); $a->x=$b; $b->x=$a;");
    emit_seed("class A extends ArrayObject{} $o=new A([1,2,3]);");
    emit_seed("class A implements IteratorAggregate{public function getIterator(){return new ArrayIterator([1,2,3]);}} $o=new A(); foreach($o as $v){}");
    emit_seed("class A implements Countable{public function count():int{return 1;}} $o=new A(); count($o);");
    emit_seed("class A implements JsonSerializable{public function jsonSerialize():mixed{return ['x'=>1];}} json_encode(new A());");
    emit_seed("class A{public readonly int $x; function __construct(){$this->x=1;}} new A();");
}
static void build_opcode_and_controlflow_payloads(void) {
    emit_seed("$a=1; if($a){$b=2;} else {$b=3;}");
    emit_seed("$a=1; switch($a){case 1:$b=1;break;default:$b=2;}");
    emit_seed("$a=0; while($a<16){$a++;}");
    emit_seed("$a=0; do{$a++;}while($a<8);");
    emit_seed("for($i=0;$i<32;$i++){$x=$i*2;}");
    emit_seed("foreach(range(1,32) as $v){$x=$v;}");
    emit_seed("$a=[1,2,3]; foreach($a as &$v){} unset($v);");
    emit_seed("$a=[1,2,3]; foreach($a as $k=>$v){$a[$k]=$v*2;}");
    emit_seed("$a=1; goto L1; L1:$a++;");
    emit_seed("try{$a=1;}catch(Throwable $e){$a=2;}finally{$a=3;}");
    emit_seed("try{throw new Exception('x');}catch(Exception $e){$a=1;}");
    emit_seed("try{$a=1/1;}finally{$a=2;}");
    emit_seed("try{goto L1;}finally{$a=1;} L1:$a=2;");
    emit_seed("$x=match(1){1=>'a',2=>'b',default=>'c'};");
    emit_seed("$x=match(rand(0,2)){0=>1,1=>2,default=>3};");
    emit_seed("$x=true ? 1 : 2;");
    emit_seed("$x=false ?: 123;");
    emit_seed("$x=null ?? 456;");
    emit_seed("$x=1 <=> 2;");
    emit_seed("$x=(1 and 0) or 1;");
    emit_seed("$x=(1 xor 0);");
    emit_seed("$x=(1<<8)>>4;");
    emit_seed("$x=~123;");
    emit_seed("$x=1+2-3*4/5;");
    emit_seed("$x=2**16;");
    emit_seed("$x=(int)'123';");
    emit_seed("$x=(float)'1.23e4';");
    emit_seed("$x=(string)123;");
    emit_seed("$x=(array)1;");
    emit_seed("$x=(object)['a'=>1];");
    emit_seed("$x=(bool)[];");
    emit_seed("$x=@strlen([]);");
    emit_seed("$x=@json_decode('{');");
    emit_seed("$x=@preg_match('/(/','x');");
    emit_seed("$x=isset($a['x']);");
    emit_seed("$x=empty($a['x']);");
    emit_seed("$a=['x'=>1]; unset($a['x']);");
    emit_seed("$a=['x'=>1]; array_key_exists('x',$a);");
    emit_seed("$a=['x'=>1]; in_array(1,$a,true);");
    emit_seed("$a=range(1,16); sort($a);");
    emit_seed("$a=range(1,16); rsort($a);");
    emit_seed("$a=['b'=>2,'a'=>1]; ksort($a);");
    emit_seed("$a=['b'=>2,'a'=>1]; krsort($a);");
    emit_seed("$a=[1,2,3]; shuffle($a);");
    emit_seed("$a=array_reverse(range(1,16));");
    emit_seed("$a=array_map(fn($x)=>$x*2, range(1,16));");
    emit_seed("$a=array_filter(range(1,16), fn($x)=>$x&1);");
    emit_seed("$a=array_reduce(range(1,16), fn($c,$v)=>$c+$v,0);");
    emit_seed("$a=array_merge(range(1,8), range(9,16));");
    emit_seed("$a=array_slice(range(1,16),4,8);");
    emit_seed("$a=array_splice($b=range(1,16),2,4);");
    emit_seed("$a=array_chunk(range(1,32),4);");
    emit_seed("$a=array_combine(range(1,8), range(9,16));");
    emit_seed("$a=array_pad([],32,'X');");
    emit_seed("$a=array_fill(0,32,'A');");
    emit_seed("$a=array_fill_keys(range(1,16),'B');");
    emit_seed("$a=array_unique([1,1,2,2,3]);");
    emit_seed("$a=array_values(['a'=>1,'b'=>2]);");
    emit_seed("$a=array_keys(['a'=>1,'b'=>2]);");
    emit_seed("$a=array_flip(['a'=>'x','b'=>'y']);");
    emit_seed("$a=array_rand(range(1,32),4);");
    emit_seed("$a=range(1,32); current($a);");
    emit_seed("$a=range(1,32); next($a);");
    emit_seed("$a=range(1,32); prev($a);");
    emit_seed("$a=range(1,32); reset($a);");
    emit_seed("$a=range(1,32); end($a);");
    emit_seed("$a=[1,2,3]; list($x,$y,$z)=$a;");
    emit_seed("$a=[1,[2,3]]; [$x,[$y,$z]]=$a;");
    emit_seed("$x=function($a){return $a+1;}; $x(1);");
    emit_seed("$x=fn($a)=>$a*2; $x(2);");
    emit_seed("$x=function()use(&$y){$y=1;}; $x();");
    emit_seed("$x=function(...$a){return count($a);}; $x(1,2,3);");
    emit_seed("function f(int|string $x):int{return (int)$x;} f('1');");
    emit_seed("function f(&$x){$x++;} $a=1; f($a);");
    emit_seed("function f(){static $x=0;$x++;} f();");
    emit_seed("function f(){yield 1;} foreach(f() as $v){}");
    emit_seed("function f(){yield from [1,2,3];} foreach(f() as $v){}");
    emit_seed("$f=new Fiber(function(){return 1;}); $f->start();");
    emit_seed("$f=new Fiber(function(){Fiber::suspend(1);}); $f->start();");
    emit_seed("$f=new Fiber(function(){Fiber::suspend(1);}); $f->start(); $f->resume();");
    emit_seed("eval('$a=1+1;');");
    emit_seed("assert(true);");
    emit_seed("assert_options(ASSERT_ACTIVE,1);");
    emit_seed("$x=gettype(123);");
    emit_seed("$x=settype($a,'string');");
    emit_seed("$x=intval('123');");
    emit_seed("$x=floatval('1.23');");
    emit_seed("$x=strval(123);");
    emit_seed("$x=boolval(1);");
    emit_seed("$x=is_array([]);");
    emit_seed("$x=is_object(new stdClass());");
    emit_seed("$x=is_string('abc');");
    emit_seed("$x=is_callable('strlen');");
    emit_seed("$x=function_exists('strlen');");
    emit_seed("$x=class_exists('stdClass');");
    emit_seed("$x=interface_exists('Iterator');");
    emit_seed("$x=trait_exists('Throwable');");
    emit_seed("$x=method_exists('ArrayObject','append');");
    emit_seed("$x=property_exists('Exception','message');");
    emit_seed("$x=defined('PHP_VERSION');");
    emit_seed("$x=constant('PHP_VERSION');");
    emit_seed("$x=get_defined_vars();");
    emit_seed("$x=get_defined_functions();");
    emit_seed("$x=get_declared_classes();");
    emit_seed("$x=get_declared_interfaces();");
    emit_seed("$x=get_loaded_extensions();");
    emit_seed("$x=memory_get_usage();");
    emit_seed("$x=memory_get_peak_usage();");
    emit_seed("$x=hrtime(true);");
    emit_seed("$x=microtime(true);");
    emit_seed("$x=uniqid('',true);");
    emit_seed("$x=random_int(1,1000);");
    emit_seed("$x=random_bytes(32);");
    emit_seed("$x=bin2hex(random_bytes(16));");
    emit_seed("$x=hash('sha256','abc');");
    emit_seed("$x=hash_hmac('sha1','abc','k');");
    emit_seed("$x=json_encode(['a'=>1]);");
    emit_seed("$x=json_decode('{\"a\":1}',true);");
    emit_seed("$x=serialize(['a'=>1]);");
    emit_seed("$x=unserialize('a:1:{s:1:\"a\";i:1;}');");
    emit_seed("$x=base64_encode('abc');");
    emit_seed("$x=base64_decode('YWJj');");
    emit_seed("$x=urlencode('a b');");
    emit_seed("$x=urldecode('a+b');");
    emit_seed("$x=http_build_query(['a'=>1]);");
    emit_seed("parse_str('a=1&b=2',$x);");
    emit_seed("$x=parse_url('http://example.com/test?a=1');");
    emit_seed("$x=explode(',', 'a,b,c');");
    emit_seed("$x=implode(',', ['a','b','c']);");
    emit_seed("$x=str_split(str_repeat('A',64),4);");
    emit_seed("$x=str_repeat('A',1024);");
    emit_seed("$x=strrev('abcdef');");
    emit_seed("$x=strtolower('ABC');");
    emit_seed("$x=strtoupper('abc');");
    emit_seed("$x=trim(' abc ');");
    emit_seed("$x=ltrim(' abc');");
    emit_seed("$x=rtrim('abc ');");
    emit_seed("$x=substr('abcdef',2,3);");
    emit_seed("$x=str_replace('a','b','aaaa');");
    emit_seed("$x=preg_match('/a+/','aaaa');");
    emit_seed("$x=preg_split('/,/','a,b,c');");
    emit_seed("$x=preg_replace('/a/','b','aaaa');");
    emit_seed("$x=pack('N',1234);");
    emit_seed("$x=unpack('N',pack('N',1234));");
    emit_seed("$x=gzcompress(str_repeat('A',64));");
    emit_seed("$x=gzuncompress(gzcompress(str_repeat('A',64)));");
    emit_seed("$x=fopen('php://memory','r+');");
    emit_seed("$x=tmpfile();");
    emit_seed("$x=new DateTime();");
    emit_seed("$x=new DateInterval('P1D');");
    emit_seed("$x=new ArrayObject([1,2,3]);");
    emit_seed("$x=new ArrayIterator([1,2,3]);");
    emit_seed("$x=new SplFixedArray(16);");
    emit_seed("$x=new SplQueue();");
    emit_seed("$x=new SplStack();");
    emit_seed("$x=new SplPriorityQueue();");
    emit_seed("$x=new SplObjectStorage();");
    emit_seed("$x=new WeakMap();");
}

static void build_engine_edgecase_payloads(void) {
    emit_seed("$a=[]; $a[]=&$a;");
    emit_seed("$a=[]; $b=&$a; $b[]=&$b;");
    emit_seed("$a=[1,2,3]; foreach($a as &$v){} foreach($a as $v){}");
    emit_seed("$a=[1]; $b=&$a[0]; $a[]=&$b;");
    emit_seed("$a=[]; for($i=0;$i<64;$i++){$a[$i]=[$i];}");
    emit_seed("$a=[]; for($i=0;$i<128;$i++){$a[str_repeat('A',$i)]=$i;}");
    emit_seed("$a=[]; for($i=0;$i<128;$i++){$a[(string)$i]=str_repeat('B',$i);}");
    emit_seed("$a=array_fill(0,256,'X');");
    emit_seed("$a=array_fill_keys(range(1,128),'Y');");
    emit_seed("$a=array_combine(range(1,64),range(65,128));");
    emit_seed("$a=array_chunk(range(1,128),8);");
    emit_seed("$a=array_map(fn($x)=>[$x,$x*$x],range(1,64));");
    emit_seed("$a=array_filter(range(1,128),fn($x)=>$x%3===0);");
    emit_seed("$a=array_reduce(range(1,64),fn($c,$v)=>$c+$v,0);");
    emit_seed("$a=[1,2,3]; array_walk($a,function(&$v){$v*=2;});");
    emit_seed("$a=[['x'=>1],['x'=>2]]; array_walk_recursive($a,function(&$v){$v++;});");
    emit_seed("$a=array_merge(range(1,16),range(17,32));");
    emit_seed("$a=array_replace(['a'=>1],['b'=>2]);");
    emit_seed("$a=array_replace_recursive(['a'=>['x'=>1]],['a'=>['y'=>2]]);");
    emit_seed("$a=array_intersect([1,2,3],[2,3,4]);");
    emit_seed("$a=array_diff([1,2,3],[2]);");
    emit_seed("$a=array_flip(['a'=>'x','b'=>'y']);");
    emit_seed("$a=array_reverse(range(1,32));");
    emit_seed("$a=array_pad([],128,'Z');");
    emit_seed("range(-128,128);");
    emit_seed("$a=range(1,32); sort($a);");
    emit_seed("$a=range(1,32); rsort($a);");
    emit_seed("$a=['z'=>1,'a'=>2]; ksort($a);");
    emit_seed("$a=['z'=>1,'a'=>2]; krsort($a);");
    emit_seed("$a=range(1,64); usort($a,fn($x,$y)=>$y<=>$x);");
    emit_seed("$a=range(1,64); uasort($a,fn($x,$y)=>$x<=>$y);");
    emit_seed("$a=['a'=>3,'b'=>1]; uksort($a,fn($x,$y)=>$x<=>$y);");
    emit_seed("$a=range(1,64); array_splice($a,8,4,[111,222]);");
    emit_seed("$a=range(1,64); array_slice($a,4,16);");
    emit_seed("$a=[1,2,3]; list($x,$y,$z)=$a;");
    emit_seed("$a=[1,[2,[3,4]]]; [$x,[$y,[$z,$w]]]=$a;");
    emit_seed("$a=function($x){return $x+1;}; $a(1);");
    emit_seed("$a=fn($x)=>$x*2; $a(8);");
    emit_seed("$a=function(...$x){return count($x);}; $a(1,2,3,4);");
    emit_seed("$a=function(&$x){$x++;}; $b=1; $a($b);");
    emit_seed("$a=function()use(&$b){$b=123;}; $a();");
    emit_seed("$a=function(){static $x=0; $x++;}; $a();");
    emit_seed("$a=function(){yield 1; yield 2;}; foreach($a() as $v){}");
    emit_seed("$a=function(){yield from [1,2,3];}; foreach($a() as $v){}");
    emit_seed("$a=function(){try{yield 1;}finally{yield 2;}}; foreach($a() as $v){}");
    emit_seed("$a=function(){yield fopen('php://memory','r');}; foreach($a() as $v){}");
    emit_seed("$a=function(){yield new stdClass();}; foreach($a() as $v){}");
    emit_seed("$f=new Fiber(function(){return 1;}); $f->start();");
    emit_seed("$f=new Fiber(function(){Fiber::suspend(1);}); $f->start();");
    emit_seed("$f=new Fiber(function(){Fiber::suspend(1); return 2;}); $f->start(); $f->resume();");
    emit_seed("$f=new Fiber(function(){return fopen('php://memory','r');}); $f->start();");
    emit_seed("$f=new Fiber(function(){return new ArrayObject([1,2,3]);}); $f->start();");
    emit_seed("$f=new Fiber(function(){return gzcompress(str_repeat('A',64));}); $f->start();");
    emit_seed("$f=new Fiber(function(){return random_bytes(32);}); $f->start();");
    emit_seed("$f=new Fiber(function(){throw new Exception('x');}); try{$f->start();}catch(Throwable $e){}");
    emit_seed("$x=(object)['a'=>1];");
    emit_seed("$x=(array)(object)['a'=>1];");
    emit_seed("$x=(string)123456;");
    emit_seed("$x=(int)'123abc';");
    emit_seed("$x=(float)'1.23e5';");
    emit_seed("$x=(bool)[];");
    emit_seed("$x=(array)null;");
    emit_seed("$x=(object)['x'=>['y'=>1]];");
    emit_seed("$x=1<=>2;");
    emit_seed("$x='a'.'b'.'c';");
    emit_seed("$x='A'^'B';");
    emit_seed("$x='A'|'B';");
    emit_seed("$x='A'&'B';");
    emit_seed("$x=~123;");
    emit_seed("$x=2**32;");
    emit_seed("$x=1<<16;");
    emit_seed("$x=65535>>4;");
    emit_seed("(1 and 0) or 1;");
    emit_seed("(1 xor 0);");
    emit_seed("$x=true?1:2;");
    emit_seed("$x=false?:123;");
    emit_seed("$x=null??456;");
    emit_seed("$x=@strlen([]);");
    emit_seed("$x=@preg_match('/(/','abc');");
    emit_seed("$x=@json_decode('{');");
    emit_seed("$x=@unserialize('bad');");
    emit_seed("$x=@gzuncompress('bad');");
    emit_seed("$x=@base64_decode('*',true);");
    emit_seed("$x=@hex2bin('xyz');");
    emit_seed("$x=isset($a['x']);");
    emit_seed("$x=empty($a['x']);");
    emit_seed("$x=array_key_exists('x',['x'=>1]);");
    emit_seed("$x=in_array(1,[1,2,3],true);");
    emit_seed("$x=property_exists('Exception','message');");
    emit_seed("$x=method_exists('ArrayObject','append');");
    emit_seed("$x=class_exists('stdClass');");
    emit_seed("$x=interface_exists('Iterator');");
    emit_seed("$x=function_exists('json_encode');");
    emit_seed("$x=defined('PHP_VERSION');");
    emit_seed("$x=get_defined_vars();");
    emit_seed("$x=get_defined_functions();");
    emit_seed("$x=get_declared_classes();");
    emit_seed("$x=get_loaded_extensions();");
    emit_seed("$x=memory_get_usage();");
    emit_seed("$x=memory_get_peak_usage();");
    emit_seed("$x=hrtime(true);");
    emit_seed("$x=microtime(true);");
    emit_seed("$x=random_int(1,100000);");
    emit_seed("$x=random_bytes(64);");
    emit_seed("$x=uniqid('',true);");
    emit_seed("$x=bin2hex(random_bytes(16));");
    emit_seed("$x=hex2bin(bin2hex(random_bytes(16)));");
    emit_seed("$x=base64_encode(random_bytes(32));");
    emit_seed("$x=base64_decode(base64_encode(random_bytes(32)));");
    emit_seed("$x=hash('sha256','abc');");
    emit_seed("$x=hash_hmac('sha1','abc','key');");
    emit_seed("$x=json_encode(['a'=>1,'b'=>2]);");
    emit_seed("$x=json_decode('{\"a\":1,\"b\":2}',true);");
    emit_seed("$x=serialize(['a'=>1,'b'=>2]);");
    emit_seed("$x=unserialize('a:1:{s:1:\"a\";i:1;}');");
    emit_seed("$x=http_build_query(['a'=>1,'b'=>2]);");
    emit_seed("parse_str('a=1&b=2',$x);");
    emit_seed("$x=parse_url('http://example.com/test?a=1');");
    emit_seed("$x=urlencode('a b c');");
    emit_seed("$x=urldecode('a+b+c');");
    emit_seed("$x=explode(',', 'a,b,c,d');");
    emit_seed("$x=implode(',', ['a','b','c']);");
    emit_seed("$x=str_repeat('A',1024);");
    emit_seed("$x=strrev('abcdef');");
    emit_seed("$x=strtolower('ABCDEF');");
    emit_seed("$x=strtoupper('abcdef');");
    emit_seed("$x=trim(' abc ');");
    emit_seed("$x=substr('abcdef',2,3);");
    emit_seed("$x=str_replace('a','b','aaaa');");
    emit_seed("$x=str_split(str_repeat('X',128),8);");
    emit_seed("$x=preg_match('/a+/','aaaaaa');");
    emit_seed("$x=preg_split('/,/','a,b,c,d');");
    emit_seed("$x=preg_replace('/a/','b','aaaa');");
    emit_seed("$x=pack('N',123456);");
    emit_seed("$x=unpack('N',pack('N',123456));");
    emit_seed("$x=gzcompress(str_repeat('A',128));");
    emit_seed("$x=gzuncompress(gzcompress(str_repeat('A',128)));");
    emit_seed("$x=fopen('php://memory','r+');");
    emit_seed("$x=fopen('php://temp','r+');");
    emit_seed("$x=tmpfile();");
    emit_seed("$x=new DateTime();");
    emit_seed("$x=new DateInterval('P1D');");
    emit_seed("$x=new ArrayObject([1,2,3]);");
    emit_seed("$x=new ArrayIterator([1,2,3]);");
    emit_seed("$x=new SplFixedArray(32);");
    emit_seed("$x=new SplQueue();");
    emit_seed("$x=new SplStack();");
    emit_seed("$x=new SplPriorityQueue();");
    emit_seed("$x=new SplObjectStorage();");
    emit_seed("$x=new WeakMap();");
    emit_seed("$x=new stdClass();");
    emit_seed("$x=new Exception('x');");
    emit_seed("$x=new RuntimeException('y');");
    emit_seed("$x=new ArrayObject(range(1,16));");
    emit_seed("$x=new ArrayIterator(range(1,16));");
    emit_seed("$x=new SplDoublyLinkedList();");
    emit_seed("$x=new SplMaxHeap();");
    emit_seed("$x=new SplMinHeap();");
    emit_seed("$x=new SplFixedArray(128);");
}
static void build_parser_and_compiler_payloads(void) {
    emit_seed("eval('$a=1+1;');");
    emit_seed("eval('function x(){return 1;} x();');");
    emit_seed("eval('class A{public $x=1;} $a=new A();');");
    emit_seed("eval('if(1){$a=1;}else{$a=2;}');");
    emit_seed("eval('switch(1){case 1:$a=1;break;}');");
    emit_seed("eval('for($i=0;$i<8;$i++){$a=$i;}');");
    emit_seed("eval('foreach(range(1,8) as $v){$x=$v;}');");
    emit_seed("eval('try{$a=1;}catch(Throwable $e){}finally{$b=2;}');");
    emit_seed("eval('function g(){yield 1;} foreach(g() as $v){}');");
    emit_seed("eval('fn($x)=>$x*2;');");
    emit_seed("eval('$x=match(1){1=>2,default=>3};');");
    emit_seed("eval('$x=null??123;');");
    emit_seed("eval('$x=false?:456;');");
    emit_seed("eval('$x=1<=>2;');");
    emit_seed("eval('$x=[1,2,3]; [$a,$b,$c]=$x;');");
    emit_seed("eval('$x=function(...$a){return count($a);}; $x(1,2,3);');");
    emit_seed("eval('$x=function(&$a){$a++;}; $b=1; $x($b);');");
    emit_seed("eval('$x=function()use(&$a){$a=1;}; $x();');");
    emit_seed("eval('$x=(object)[\"a\"=>1];');");
    emit_seed("eval('$x=(array)(object)[\"a\"=>1];');");
    emit_seed("eval('$x=(string)123;');");
    emit_seed("eval('$x=(int)\"123abc\";');");
    emit_seed("eval('$x=(float)\"1.23e5\";');");
    emit_seed("eval('$x=(bool)[];');");
    emit_seed("eval('$x=1<<16;');");
    emit_seed("eval('$x=65535>>4;');");
    emit_seed("eval('$x=2**32;');");
    emit_seed("eval('$x=~123;');");
    emit_seed("eval('$x=\"A\"^\"B\";');");
    emit_seed("eval('$x=\"A\"|\"B\";');");
    emit_seed("eval('$x=\"A\"&\"B\";');");
    emit_seed("eval('$x=1+2-3*4/5;');");
    emit_seed("eval('$x=true?1:2;');");
    emit_seed("eval('$x=(1 and 0) or 1;');");
    emit_seed("eval('$x=(1 xor 0);');");
    emit_seed("eval('$x=@strlen([]);');");
    emit_seed("eval('$x=@preg_match(\"/(/\",\"abc\");');");
    emit_seed("eval('$x=@json_decode(\"{\");');");
    emit_seed("eval('$x=@base64_decode(\"*\",true);');");
    emit_seed("eval('$x=isset($a[\"x\"]);');");
    emit_seed("eval('$x=empty($a[\"x\"]);');");
    emit_seed("eval('$x=array_key_exists(\"x\",[\"x\"=>1]);');");
    emit_seed("eval('$x=in_array(1,[1,2,3],true);');");
    emit_seed("eval('$x=function_exists(\"strlen\");');");
    emit_seed("eval('$x=class_exists(\"stdClass\");');");
    emit_seed("eval('$x=interface_exists(\"Iterator\");');");
    emit_seed("eval('$x=method_exists(\"ArrayObject\",\"append\");');");
    emit_seed("eval('$x=property_exists(\"Exception\",\"message\");');");
    emit_seed("eval('$x=get_defined_vars();');");
    emit_seed("eval('$x=get_defined_functions();');");
    emit_seed("eval('$x=get_declared_classes();');");
    emit_seed("eval('$x=get_loaded_extensions();');");
    emit_seed("eval('$x=memory_get_usage();');");
    emit_seed("eval('$x=memory_get_peak_usage();');");
    emit_seed("eval('$x=hrtime(true);');");
    emit_seed("eval('$x=microtime(true);');");
    emit_seed("eval('$x=random_int(1,1000);');");
    emit_seed("eval('$x=random_bytes(32);');");
    emit_seed("eval('$x=uniqid(\"\",true);');");
    emit_seed("eval('$x=bin2hex(random_bytes(16));');");
    emit_seed("eval('$x=hex2bin(bin2hex(random_bytes(16)));');");
    emit_seed("eval('$x=base64_encode(random_bytes(32));');");
    emit_seed("eval('$x=base64_decode(base64_encode(random_bytes(32)));');");
    emit_seed("eval('$x=hash(\"sha256\",\"abc\");');");
    emit_seed("eval('$x=hash_hmac(\"sha1\",\"abc\",\"key\");');");
    emit_seed("eval('$x=json_encode([\"a\"=>1]);');");
    emit_seed("eval('$x=json_decode(\"{\\\"a\\\":1}\",true);');");
    emit_seed("eval('$x=serialize([\"a\"=>1]);');");
    emit_seed("eval('$x=unserialize(\"a:1:{s:1:\\\"a\\\";i:1;}\");');");
    emit_seed("eval('$x=http_build_query([\"a\"=>1]);');");
    emit_seed("eval('parse_str(\"a=1&b=2\",$x);');");
    emit_seed("eval('$x=parse_url(\"http://example.com/test?a=1\");');");
    emit_seed("eval('$x=urlencode(\"a b c\");');");
    emit_seed("eval('$x=urldecode(\"a+b+c\");');");
    emit_seed("eval('$x=explode(\",\",\"a,b,c,d\");');");
    emit_seed("eval('$x=implode(\",\",[\"a\",\"b\",\"c\"]);');");
    emit_seed("eval('$x=str_repeat(\"A\",1024);');");
    emit_seed("eval('$x=strrev(\"abcdef\");');");
    emit_seed("eval('$x=strtolower(\"ABCDEF\");');");
    emit_seed("eval('$x=strtoupper(\"abcdef\");');");
    emit_seed("eval('$x=trim(\" abc \");');");
    emit_seed("eval('$x=substr(\"abcdef\",2,3);');");
    emit_seed("eval('$x=str_replace(\"a\",\"b\",\"aaaa\");');");
    emit_seed("eval('$x=str_split(str_repeat(\"X\",128),8);');");
    emit_seed("eval('$x=preg_match(\"/a+/\",\"aaaaaa\");');");
    emit_seed("eval('$x=preg_split(\"/,/\",\"a,b,c,d\");');");
    emit_seed("eval('$x=preg_replace(\"/a/\",\"b\",\"aaaa\");');");
    emit_seed("eval('$x=pack(\"N\",123456);');");
    emit_seed("eval('$x=unpack(\"N\",pack(\"N\",123456));');");
    emit_seed("eval('$x=gzcompress(str_repeat(\"A\",128));');");
    emit_seed("eval('$x=gzuncompress(gzcompress(str_repeat(\"A\",128)));');");
    emit_seed("eval('$x=fopen(\"php://memory\",\"r+\");');");
    emit_seed("eval('$x=fopen(\"php://temp\",\"r+\");');");
    emit_seed("eval('$x=tmpfile();');");
    emit_seed("eval('$x=new DateTime();');");
    emit_seed("eval('$x=new DateInterval(\"P1D\");');");
    emit_seed("eval('$x=new ArrayObject([1,2,3]);');");
    emit_seed("eval('$x=new ArrayIterator([1,2,3]);');");
    emit_seed("eval('$x=new SplFixedArray(32);');");
    emit_seed("eval('$x=new SplQueue();');");
    emit_seed("eval('$x=new SplStack();');");
    emit_seed("eval('$x=new SplPriorityQueue();');");
    emit_seed("eval('$x=new SplObjectStorage();');");
    emit_seed("eval('$x=new WeakMap();');");
    emit_seed("eval('$x=new stdClass();');");
    emit_seed("eval('$x=new Exception(\"x\");');");
    emit_seed("eval('$x=new RuntimeException(\"y\");');");
    emit_seed("eval('$x=new ArrayObject(range(1,16));');");
    emit_seed("eval('$x=new ArrayIterator(range(1,16));');");
    emit_seed("eval('$x=new SplDoublyLinkedList();');");
    emit_seed("eval('$x=new SplMaxHeap();');");
    emit_seed("eval('$x=new SplMinHeap();');");
    emit_seed("eval('$x=new SplFixedArray(128);');");
    emit_seed("eval('class A{public $x=1;}');");
    emit_seed("eval('class B extends Exception{}');");
    emit_seed("eval('interface I{public function x();}');");
    emit_seed("eval('trait T{public function y(){return 1;}}');");
    emit_seed("eval('enum E:int{case A=1;case B=2;}');");
    emit_seed("eval('readonly class R{public int $x; public function __construct(){ $this->x=1; }}');");
    emit_seed("eval('function z(int|string $x):int{return (int)$x;} z(\"1\");');");
    emit_seed("eval('declare(strict_types=1); $x=1;');");
    emit_seed("eval('namespace X; class A{}');");
    emit_seed("eval('use Exception as E; $x=new E(\"a\");');");
}

int main(int argc, char **argv) {
    ensure_corpus_environment();
    build_zend_hash_payloads();
    build_zend_alloc_payloads();
    build_generator_and_fiber_payloads();
    build_reflection_and_object_payloads();
    build_opcode_and_controlflow_payloads();
    build_engine_edgecase_payloads();
    build_parser_and_compiler_payloads();
    printf("Total payloads compiled and generated: %d\n", current_seed_id - 1);
    return 0;
}
